### PR TITLE
Hold Tabs/ContentSwitch inner component state while switching between screens sizes

### LINKED ISSUE #311: Incorrect behavior inside Tab component while switching screen size between mobile and desktop view
### Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository?
- [ ] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Versions

You can get this information from executing `npm version`.

### Description

Peek 2020-11-23 13-29

### Steps to Reproduce

1. Open https://gso9l.csb.app/ or https://codesandbox.io/s/musing-shape-gso9l
2. Click on a primary button to increase a counter
3. Change the size of the window and verify the behavior

**Expected behavior:** No state reset

**Actual behavior:** The component inside is being re-mounted and state reset

**Environment details:** Any OS, any browser

### Possible Solution

TBD

### PR DESCRIPTION
**Pull request by dimabory**
### Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### Description

Fixes #311 

Components involved:
 - Tabs
 - ContentSwitch

Some hints for understanding the core difference:

- Before

#311-before

- After

#311-after

### CODE REVIEW

File: src/components/TabControl/index.tsx [hunk 1]
```diff
@@ -125,3 +136,92 @@ export class TabControl extends React.PureComponent<TabControlProps, TabControlS
     return render(items);
```
Comment (dimabory) [inline src/components/TabControl/index.tsx:136]: FYI that is the actual place, which was causing the re-rendering.

**Review by boromo — APPROVED** [review]
